apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.network/bookingdomain: "true"
    io.kompose.service: otasoft-booking
  name: otasoft-booking
spec:
  containers:
    - env:
        - name: POSTGRES_DATABASE
        - name: POSTGRES_HOST
          value: otasoft-booking-db
        - name: POSTGRES_PASSWORD
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USERNAME
        - name: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_VHOST
        - name: RABBITMQ_FIRST_HOST_PORT
          value: "5672"
        - name: RABBITMQ_NODENAME
          value: otasoft-api-rabbitmq
      image: otasoft-booking:dev
      name: otasoft-booking
      resources: {}
  restartPolicy: OnFailure
status: {}
